# Generated by Django 4.2.7 on 2023-12-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_post_post_id_alter_post_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
