# Generated by Django 4.1 on 2024-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_post_id_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
