# Generated by Django 4.1 on 2024-01-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0007_alter_post_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.TextField(null=True),
        ),
    ]
