services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    command: python manage.py runserver
    volumes:
      - backend-vol:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - djangonetwork

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  djangonetwork:
    driver: bridge

volumes:
  db-vol:
  backend-vol: