services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    command: sh start.sh
    volumes:
      - backend-vol:/code
    ports:
      - "8000:8000"
    networks:
      - djangonetwork

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  db-vol:
  backend-vol: