name: Docker Builder
on:
  push:
    branches: ["docker"]
  pull_request:
    branches: [ "dev" ]
jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push to GitHub Container Registry
        run: docker-compose -f docker-compose.yml push
